### ISSUE TITLE
Upload helper doesn't work with ember-test-helpers@1.0.0

### ISSUE THREAD

**Issue by andreyfel** [adopted-ember-addons/ember-file-upload#189]
When we use 'upload' test helper with ember-test-helpers@1.0.0 there is an exception.

TypeError: Cannot read property 'length' of undefined
    at buildFileEvent (http://localhost:4202/assets/tests.js:810:15)
    at fireEvent (http://localhost:4202/assets/tests.js:695:15)
    at http://localhost:4202/assets/tests.js:1050:30
    at tryCatcher (http://localhost:4202/assets/vendor.js:71571:21)
    at invokeCallback (http://localhost:4202/assets/vendor.js:71743:33)
    at publish (http://localhost:4202/assets/vendor.js:71729:9)
    at http://localhost:4202/assets/vendor.js:63970:16
    at invokeWithOnError (http://localhost:4202/assets/vendor.js:39668:28)
    at Queue.flush (http://localhost:4202/assets/vendor.js:39571:25)
    at DeferredActionQueues.flush (http://localhost:4202/assets/vendor.js:39738:31)

It is probably related to this change: https://github.com/emberjs/ember-test-helpers/pull/428

**Comment by raphaelns-developer** [comment]
When the fix will be applied?
