### ISSUE TITLE
`ember test` arrow.svg error (Windows?)

### ISSUE THREAD

**Issue by XaserAcheron** [adopted-ember-addons/ember-file-upload#36]
I can't seem to get `ember test` to run. It fails with the following error when trying to clean up after building:

```
C:\Code\GitHub\forks\ember-file-upload>ember test
DEPRECATION: Addon test support files were detected in `C:/Code/GitHub/forks/ember-file-upload/node_modules/ember-cli-test-loader/addon-test-support`, but no JavaScript preprocessors were found for `ember-cli-test-loader`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to `dependencies` (NOT `devDependencies`) in `ember-cli-test-loader`'s `package.json`.
cleaning up...
Build failed.
File: arrow.svg
The Broccoli Plugin: [SVGOFilter] failed with:Error: ENOENT: no such file or directory, open 'C:\Users\XaserAcheron\AppData\Local\Temp\if-you-need-to-delete-this-open-an-issue-async-disk-cache\d0a26e6a212dbbaf16034028ed97fb47dc71c26b\{"persist":true,"svgoConfig":{}}337a3cdfc8b191f654659e3ce12929b1'
    at Error (native)

The broccoli plugin was instantiated at:
    at SVGOFilter.Plugin (C:\Code\GitHub\forks\ember-file-upload\node_modules\broccoli-persistent-filter\node_modules\broccoli-plugin\index.js:7:31)
    at SVGOFilter.Filter [as constructor] (C:\Code\GitHub\forks\ember-file-upload\node_modules\broccoli-persistent-filter\index.js:60:10)
    at new SVGOFilter (C:\Code\GitHub\forks\ember-file-upload\node_modules\broccoli-svg-optimizer\index.js:15:10)
    at Class.<anonymous> (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-svg-jar\lib\index.js:149:12)
    at Class.memoized [as optimizedSvgsFor] (C:\Code\GitHub\forks\ember-file-upload\node_modules\lodash\lodash.js:10551:27)
    at Class.<anonymous> (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-svg-jar\lib\index.js:158:50)
    at Class.memoized [as svgsFor] (C:\Code\GitHub\forks\ember-file-upload\node_modules\lodash\lodash.js:10551:27)
    at Class.getInlineStrategyTree (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-svg-jar\lib\index.js:199:34)
    at Class.treeForApp (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-svg-jar\lib\index.js:113:23)
    at Class._treeFor (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-cli\lib\models\addon.js:517:33)
    at Class.treeFor (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-cli\lib\models\addon.js:477:21)
    at project.addons.map.addon (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-cli\lib\broccoli\ember-app.js:525:20)
    at Array.map (native)
    at EmberAddon.EmberApp.addonTreesFor (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-cli\lib\broccoli\ember-app.js:523:30)
    at EmberAddon.EmberApp.appAndDependencies (C:\Code\GitHub\forks\ember-file-upload\node_modules\ember-cli\lib\broccoli\ember-app.js:1092:10)
```
Note the random bit of JSON that gets plunked into the async-disk-cache path. I don't think that's supposed to be there. :P

This may end up being an upstream thing, but it's worth opening here just to get an expert pair of eyes on it, I think.

Further info: I use Windows 8.1, and this wouldn't be the first time the OS difference caused an "oops" somewhere, so it's worth mentioning perhaps. Hooray for being an oddball. :P

**Comment by tim-evans** [comment]
Hrrm. Probably related to ember-svg-jar.

**Comment by tim-evans** [comment]
Also, `if-you-need-to-delete-this-open-an-issue-async-disk-cache` 😂

**Comment by XaserAcheron** [comment]
That is one of my new favorite names for things. :P

[FWIW, I did delete it and try it again and it didn't make any difference, so I don't suspect async-disk-cache is actually at fault. But thanks for the chuckle, Stef. :P]

**Comment by tim-evans** [comment]
:D

**Comment by XaserAcheron** [comment]
Well, sure enough, looks like someone else ran into [the same thing](https://github.com/ivanvotti/ember-svg-jar/issues/24) -- Windows-specific, of course; looks like it doesn't like the colon character in that filename.

I'll see if I can investigate this; keep the dev train rolling. :P

**Comment by XaserAcheron** [comment]
PR submitted. Tests run great now on the fixed `broccoli-svg-optimizer` branch, so this ought to be closeable once everything flows downstream.
