### ISSUE TITLE
Readme example does not work

### ISSUE THREAD

**Issue by wangsongyuf** [adopted-ember-addons/ember-file-upload#77]
I am new to the ember thing and trying to use this to allow user to upload pics. However, after copying the code from readme  and adding dependencies.  I got this error:
```
index.js:142 Uncaught EmberError {stack: "Error: Assertion Failed: [ember-route-action-helpe…(http://localhost:4200/assets/vendor.js:26429:57)", description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: [ember-route-action-helper] Unable to find action uploadImage", …}code: undefineddescription: undefinedfileName: undefinedlineNumber: undefinedmessage: "Assertion Failed: [ember-route-action-helper] Unable to find action uploadImage"name: "Error"number: undefinedstack: "Error: Assertion Failed: [ember-route-action-helper] Unable to find action uploadImage
   at new EmberError (http://localhost:4200/assets/vendor.js:24967:25)
   at Object.assert (http://localhost:4200/assets/vendor.js:25209:15)
   at http://localhost:4200/assets/vendor.js:74252:38
   at runInDebug (http://localhost:4200/assets/vendor.js:25298:7)
   at Class.compute (http://localhost:4200/assets/vendor.js:74248:7)
   at ClassBasedHelperReference.compute (http://localhost:4200/assets/vendor.js:33582:23)
   at ClassBasedHelperReference.value (http://localhost:4200/assets/vendor.js:33191:45)
   at CapturedNamedArguments.value (http://localhost:4200/assets/vendor.js:12899:43)
   at processComponentArgs (http://localhost:4200/assets/vendor.js:33078:27)
   at CurlyComponentManager.create (http://localhost:4200/assets/vendor.js:26429:57)"__proto__: ExtendableBuiltinconstructor: ƒ EmberError(message)__proto__: Error
assert @ index.js:142
(anonymous) @ route-action.js:73
runInDebug @ index.js:231
compute @ route-action.js:69
compute @ references.js:461
value @ references.js:70
value @ runtime.js:688
processComponentArgs @ process-args.js:12
create @ curly.js:169
(anonymous) @ runtime.js:1671
evaluate @ runtime.js:70
next @ runtime.js:7244
next @ runtime.js:7315
RootState.render @ renderer.js:62
exports.runInTransaction @ ember-metal.js:674
_renderRoots @ renderer.js:341
_renderRootsTransaction @ renderer.js:379
_renderRoot @ renderer.js:299
_appendDefinition @ renderer.js:209
appendOutletView @ renderer.js:192
invoke @ backburner.js:272
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:454
run @ backburner.js:538
join @ backburner.js:545
run$1.join @ ember-metal.js:4367
hash.success @ rest.js:613
fire @ jquery.js:3317
fireWith @ jquery.js:3447
done @ jquery.js:9272
(anonymous) @ jquery.js:9514
XMLHttpRequest.send (async)
send @ jquery.js:9566
ajax @ jquery.js:9173
_ajaxRequest @ rest.js:629
(anonymous) @ rest.js:625
initializePromise @ rsvp.js:453
Promise @ rsvp.js:929
ajax @ rest.js:608
findAll @ rest.js:358
_findAll @ -private.js:8778
_fetchAll @ -private.js:11474
findAll @ -private.js:11442
model @ application.js:9
deserialize @ route.js:945
applyHook @ router.js:244
runSharedModelHook @ router.js:840
getModel @ router.js:1038
(anonymous) @ router.js:97
tryCatch @ rsvp.js:411
invokeCallback @ rsvp.js:424
publish @ rsvp.js:394
(anonymous) @ rsvp.js:14
invoke @ backburner.js:274
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:454
run @ backburner.js:538
join @ backburner.js:545
run$1.join @ ember-metal.js:4367
(anonymous) @ ember-metal.js:4430
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
```

I am not sure why it happens. Can anyone help me with this?
I only copied Recipes and Integration code

**Comment by wangsongyuf** [comment]
I tried to use the code as component. I parses correctly but fail on uploading. 
```
ember-metal.js:3994 TypeError: this.modelFor is not a function
    at Class._callee$ (http://localhost:4200/assets/popular-media-app.js:73:30)
    at tryCatch (http://localhost:4200/assets/vendor.js:68:40)
    at Generator.invoke [as _invoke] (http://localhost:4200/assets/vendor.js:342:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:4200/assets/vendor.js:101:21)
    at Class._resumeGenerator (http://localhost:4200/assets/vendor.js:69615:46)
    at Class._handleResolvedContinueValue (http://localhost:4200/assets/vendor.js:69737:12)
    at Class._proceed (http://localhost:4200/assets/vendor.js:69701:14)
    at Class._scheduleProceed (http://localhost:4200/assets/vendor.js:69690:14)
    at Class._start (http://localhost:4200/assets/vendor.js:69448:12)
    at Class._startTaskInstance (http://localhost:4200/assets/vendor.js:69093:20)
```

**Comment by donaldwasserman** [comment]
you need to add the right actions param on your route. You cann tell this from the end of the error code you pasted that says `Assertion Failed: [ember-route-action-helper] Unable to find action uploadImage`

Actions need to look like this: 

```js 
export default Route.extend({
  model(params) {
   return this.store.findRecord('thing', params.whatever);
  }
  actions: {
    yourActionNameHere(argument) {
      //do stuff here 
   }
  }
});
``` 

For your second comment, `.modelFor`: It's part of ember-data's `DS.Store` class. It gets automatically injected into all ember routes.

You'll need to inject the store into your component: 

```js 
//MyComponent.js
import {inject as service} from '@ember/service';
import Component from '@ember/component';

export default Component.extend({
  store: service(),
  actions: {
    yourAction(file) {
      this.get('store').modelFor() //....the rest of your code. 
})
```

**Comment by tim-evans** [comment]
Thanks so much for the help, @donaldwasserman ❤️

**Comment by tim-evans** [comment]
https://github.com/tim-evans/ember-file-upload/issues/122

**Comment by jelhan** [comment]
Documentation contains an example using an action ([https://adopted-ember-addons.github.io/ember-file-upload/docs/aws]) and an ember-concurrency task ([https://adopted-ember-addons.github.io/ember-file-upload/docs/integration]).
