### ISSUE TITLE
missing tracked built ins

### ISSUE THREAD

**Issue by mcfiredrill** [adopted-ember-addons/ember-file-upload#982]
```
Uncaught (in promise) Error: Could not find module `tracked-built-ins` imported from `(require)`
    at missingModule (loader.js:247:1)
    at findModule (loader.js:258:1)
    at requireModule (loader.js:24:1)
    at tracked-built-ins (chunk.app.78ae7e1….js:194:18)
    at __webpack_require__ (chunk.app.78ae7e1….js:238:42)
    at eval (file-queue-a488b012.js:21:75)
    at ./node_modules/.pnpm/ember-file-upload@8.2.0_@ember+test-helpers@2.8.1__ncxixvef3qfcbfkotwgrc427d4/node_modules/ember-file-upload/dist/file-queue-a488b012.js (chunk.vendors-node_m…88abc21f1.js:1059:1)
    at __webpack_require__ (chunk.app.78ae7e1….js:238:42)
    at eval (file-dropzone.js:21:81)
    at ./node_modules/.pnpm/ember-file-upload@8.2.0_@ember+test-helpers@2.8.1__ncxixvef3qfcbfkotwgrc427d4/node_modules/ember-file-upload/dist/components/file-dropzone.js (chunk.vendors-node_m…88abc21f1.js:1037:1)
```

**Comment by mcfiredrill** [comment]
Should this be a dep not a devDep? 
https://github.com/adopted-ember-addons/ember-file-upload/blob/master/ember-file-upload/package.json#L91

**Comment by mcfiredrill** [comment]
Should this be a dep not a devDep? 
https://github.com/adopted-ember-addons/ember-file-upload/blob/master/ember-file-upload/package.json#L91

**Comment by jelhan** [comment]
It's a peer dependency, which the consuming application is expected to satisfy: https://github.com/adopted-ember-addons/ember-file-upload/blob/74e58d594dc95e9620ddcb6efba8335a608eeb96/ember-file-upload/package.json#L102

Sadly not all package manager ensure that peer dependencies are satisfied on install...

**Comment by gilest** [comment]
Yes, this used to be a regular dependency but since v8.0.0 we've moved ember blueprint-provided packages to peerDependencies.

This is documented in the [Upgrade guide](https://ember-file-upload.pages.dev/docs/upgrade-guide).
